// Nóminas oficiales del Mundial 2026 por selección, usadas en el selector con
// buscador de "Goleador del torneo" (Apuestas especiales).
//
// Las claves coinciden EXACTAMENTE con `TEAMS_MUNDIAL_2026` (constants.js) para
// poder reutilizar `code(equipo)` y mostrar la bandera de cada jugador.
//
// Fuente: convocatorias oficiales de 26 jugadores entregadas a la FIFA el 1 de
// junio y anunciadas el 2 de junio de 2026 (verificadas contra Wikipedia
// "2026 FIFA World Cup squads", ESPN y Al Jazeera). Última actualización:
// junio de 2026. Para ajustes puntuales basta con editar este archivo.

import { code } from "./constants";

export const JUGADORES_MUNDIAL_2026 = {
  Alemania: [
    "Manuel Neuer", "Oliver Baumann", "Alexander Nübel",
    "Antonio Rüdiger", "Jonathan Tah", "David Raum", "Nico Schlotterbeck",
    "Waldemar Anton", "Malick Thiaw", "Nathaniel Brown", "Pascal Groß",
    "Joshua Kimmich", "Felix Nmecha", "Florian Wirtz", "Jamal Musiala",
    "Leon Goretzka", "Angelo Stiller", "Lennart Karl", "Nadiem Amiri",
    "Aleksandar Pavlović", "Kai Havertz", "Leroy Sané", "Nick Woltemade",
    "Jamie Leweling", "Deniz Undav", "Maximilian Beier",
  ],
  "Arabia Saudita": [
    "Mohammed Al-Owais", "Nawaf Al-Aqidi", "Ahmed Al-Kassar",
    "Abdulelah Al-Amri", "Hassan Tambakti", "Jehad Thikri", "Ali Lajami",
    "Hassan Kadesh", "Saud Abdulhamid", "Mohammed Abu Al-Shamat", "Ali Majrashi",
    "Moteb Al-Harbi", "Nawaf Boushal", "Sultan Al-Ghannam", "Mohammed Kanno",
    "Abdullah Al-Khaibari", "Ziyad Al-Johani", "Nasser Al-Dawsari",
    "Musab Al-Juwayr", "Alaa Al-Hajji", "Ayman Yahya", "Salem Al-Dawsari",
    "Khalid Al-Ghannam", "Firas Al-Buraikan", "Saleh Al-Shehri", "Abdullah Al-Hamdan",
  ],
  Argelia: [
    "Luca Zidane", "Oussama Benbot", "Melvin Mastil",
    "Rafik Belghali", "Samir Chergui", "Rayan Aït-Nouri", "Jaouen Hadjam",
    "Aïssa Mandi", "Ramy Bensebaini", "Zineddine Belaïd", "Achref Abada",
    "Mohamed Amine Tougaï", "Nabil Bentaleb", "Hicham Boudaoui", "Houssem Aouar",
    "Farès Chaïbi", "Ibrahim Maza", "Yacine Titraoui", "Ramiz Zerrouki",
    "Mohamed Amoura", "Nadhir Benbouali", "Adil Boulbina", "Farès Ghedjemis",
    "Amine Gouiri", "Anis Hadj Moussa", "Riyad Mahrez",
  ],
  Argentina: [
    "Emiliano Martínez", "Gerónimo Rulli", "Juan Musso",
    "Nahuel Molina", "Gonzalo Montiel", "Cristian Romero", "Lisandro Martínez",
    "Nicolás Otamendi", "Leonardo Balerdi", "Facundo Medina", "Nicolás Tagliafico",
    "Rodrigo De Paul", "Alexis Mac Allister", "Enzo Fernández", "Leandro Paredes",
    "Giovani Lo Celso", "Exequiel Palacios", "Valentín Barco", "Lionel Messi",
    "Lautaro Martínez", "Julián Álvarez", "Nico González", "Thiago Almada",
    "Giuliano Simeone", "Nico Paz", "José Manuel López",
  ],
  Australia: [
    "Mathew Ryan", "Paul Izzo", "Patrick Beach",
    "Aziz Behich", "Jordan Bos", "Cameron Burgess", "Alessandro Circati",
    "Milos Degenek", "Jason Geria", "Lucas Herrington", "Jacob Italiano",
    "Harry Souttar", "Kai Trewin", "Cameron Devlin", "Ajdin Hrustić",
    "Jackson Irvine", "Connor Metcalfe", "Paul Okon-Engstler", "Aiden O'Neill",
    "Nestory Irankunda", "Mathew Leckie", "Awer Mabil", "Mohamed Touré",
    "Nishan Velupillay", "Cristian Volpato", "Tete Yengi",
  ],
  Austria: [
    "Patrick Pentz", "Alexander Schlager", "Florian Wiegele",
    "David Affengruber", "David Alaba", "Kevin Danso", "Marco Friedl",
    "Philipp Lienhart", "Phillipp Mwene", "Stefan Posch", "Alexander Prass",
    "Michael Svoboda", "Christoph Baumgartner", "Carney Chukwuemeka", "Florian Grillitsch",
    "Konrad Laimer", "Marcel Sabitzer", "Xaver Schlager", "Romano Schmid",
    "Alessandro Schöpf", "Nicolas Seiwald", "Paul Wanner", "Patrick Wimmer",
    "Marko Arnautović", "Michael Gregoritsch", "Saša Kalajdžić",
  ],
  Bélgica: [
    "Thibaut Courtois", "Senne Lammens", "Mike Penders",
    "Timothy Castagne", "Zeno Debast", "Maxim De Cuyper", "Koni De Winter",
    "Brandon Mechele", "Thomas Meunier", "Nathan Ngoy", "Joaquin Seys",
    "Arthur Theate", "Kevin De Bruyne", "Amadou Onana", "Nicolas Raskin",
    "Youri Tielemans", "Hans Vanaken", "Axel Witsel", "Charles De Ketelaere",
    "Jérémy Doku", "Matías Fernández-Pardo", "Romelu Lukaku", "Dodi Lukebakio",
    "Diego Moreira", "Alexis Saelemaekers", "Leandro Trossard",
  ],
  "Bosnia y Herzegovina": [
    "Nikola Vasilj", "Martin Zlomislić", "Mladen Jurkas",
    "Sead Kolašinac", "Amar Dedić", "Nihad Mujakić", "Nikola Katić",
    "Tarik Muharemović", "Stjepan Radeljić", "Dennis Hadžikadunić", "Nidal Čelik",
    "Amir Hadžiahmetović", "Ivan Šunjić", "Ivan Bašić", "Dženis Burnić",
    "Ermin Mahmić", "Benjamin Tahirović", "Amar Memić", "Armin Gigović",
    "Kerim Alajbegović", "Esmir Bajraktarević", "Ermedin Demirović", "Jovo Lukić",
    "Samed Baždar", "Haris Tabaković", "Edin Džeko",
  ],
  Brasil: [
    "Alisson", "Ederson", "Weverton",
    "Marquinhos", "Danilo", "Alex Sandro", "Gabriel Magalhães",
    "Bremer", "Wesley", "Roger Ibañez", "Douglas Santos", "Léo Pereira",
    "Casemiro", "Lucas Paquetá", "Bruno Guimarães", "Fabinho", "Danilo (Botafogo)",
    "Neymar", "Vinícius Júnior", "Raphinha", "Gabriel Martinelli",
    "Matheus Cunha", "Endrick", "Luiz Henrique", "Igor Thiago", "Rayan",
  ],
  "Cabo Verde": [
    "Vozinha", "Márcio Rosa", "CJ dos Santos",
    "Steven Moreira", "Wagner Pina", "João Paulo Fernandes", "Sidny Lopes Cabral",
    "Logan Costa", "Pico", "Kelvin Pires", "Stopira", "Diney",
    "Jamiro Monteiro", "Telmo Arcanjo", "Yannick Semedo", "Laros Duarte",
    "Deroy Duarte", "Kevin Pina", "Ryan Mendes", "Willy Semedo", "Garry Rodrigues",
    "Jovane Cabral", "Nuno da Costa", "Dailon Livramento", "Gilson Benchimol", "Hélio Varela",
  ],
  Canadá: [
    "Dayne St. Clair", "Maxime Crépeau", "Owen Goodman",
    "Moïse Bombito", "Derek Cornelius", "Alphonso Davies", "Luc de Fougerolles",
    "Alistair Johnston", "Alfie Jones", "Richie Laryea", "Niko Sigur",
    "Joel Waterman", "Ali Ahmed", "Tajon Buchanan", "Mathieu Choinière",
    "Stephen Eustáquio", "Marcelo Flores", "Ismaël Koné", "Liam Millar",
    "Jonathan Osorio", "Nathan Saliba", "Jacob Shaffelburg", "Jonathan David",
    "Promise David", "Cyle Larin", "Tani Oluwaseyi",
  ],
  Chequia: [
    "Matěj Kovář", "Jindřich Staněk", "Lukáš Horníček",
    "David Zima", "Tomáš Holeš", "Robin Hranáč", "Vladimír Coufal",
    "Štěpán Chaloupek", "Ladislav Krejčí", "David Jurásek", "Jaroslav Zelený",
    "David Douděra", "Vladimír Darida", "Lukáš Červ", "Lukáš Provod",
    "Michal Sadílek", "Tomáš Souček", "Alexandr Sojka", "Hugo Sochůrek",
    "Adam Hložek", "Patrik Schick", "Jan Kuchta", "Mojmír Chytil",
    "Pavel Šulc", "Tomáš Chorý", "Denis Višinský",
  ],
  Colombia: [
    "Camilo Vargas", "David Ospina", "Álvaro Montero",
    "Daniel Muñoz", "Davinson Sánchez", "Johan Mojica", "Jhon Lucumí",
    "Santiago Arias", "Yerry Mina", "Willer Ditta", "Deiver Machado",
    "James Rodríguez", "Richard Ríos", "Jhon Arias", "Juan Fernando Quintero",
    "Gustavo Puerta", "Juan Camilo Portilla", "Jorge Carrascal", "Jaminton Campaz",
    "Jefferson Lerma", "Kevin Castaño", "Luis Díaz", "Luis Suárez",
    "Jhon Córdoba", "Juan Camilo Hernández", "Carlos Andrés Gómez",
  ],
  "Corea del Sur": [
    "Kim Seung-gyu", "Song Bum-keun", "Jo Hyeon-woo",
    "Lee Han-beom", "Kim Min-jae", "Kim Tae-hyeon", "Lee Tae-seok",
    "Cho Wi-je", "Kim Moon-hwan", "Park Jin-seob", "Seol Young-woo",
    "Jens Castrop", "Lee Gi-hyuk", "Hwang In-beom", "Paik Seung-ho",
    "Lee Jae-sung", "Hwang Hee-chan", "Bae Jun-ho", "Lee Kang-in",
    "Yang Hyun-jun", "Kim Jin-gyu", "Eom Ji-sung", "Lee Dong-gyeong",
    "Son Heung-min", "Cho Gue-sung", "Oh Hyeon-gyu",
  ],
  "Costa de Marfil": [
    "Yahia Fofana", "Mohamed Koné", "Alban Lafont",
    "Emmanuel Agbadou", "Christopher Opéri", "Ousmane Diomande", "Guéla Doué",
    "Ghislain Konan", "Odilon Kossounou", "Evan Ndicka", "Wilfried Singo",
    "Seko Fofana", "Parfait Guiagon", "Christ Inao Oulaï", "Franck Kessié",
    "Ibrahim Sangaré", "Jean-Michaël Seri", "Simon Adingra", "Ange-Yoan Bonny",
    "Amad Diallo", "Oumar Diakité", "Yan Diomande", "Evann Guessand",
    "Nicolas Pépé", "Bazoumana Touré", "Elvy Wahi",
  ],
  Croacia: [
    "Dominik Livaković", "Dominik Kotarski", "Ivor Pandur",
    "Joško Gvardiol", "Duje Ćaleta-Car", "Josip Šutalo", "Josip Stanišić",
    "Marin Pongračić", "Martin Erlić", "Luka Vušković", "Luka Modrić",
    "Mateo Kovačić", "Mario Pašalić", "Nikola Vlašić", "Luka Sučić",
    "Martin Baturina", "Kristijan Jakić", "Petar Sučić", "Nikola Moro",
    "Toni Fruk", "Ivan Perišić", "Andrej Kramarić", "Ante Budimir",
    "Marco Pašalić", "Petar Musa", "Igor Matanović",
  ],
  Curazao: [
    "Eloy Room", "Trevor Doornbusch", "Tyrick Bodak",
    "Shurandy Sambo", "Juriën Gaari", "Roshon van Eijma", "Sherel Floranus",
    "Armando Obispo", "Joshua Brenet", "Riechedly Bazoer", "Deveron Fonville",
    "Godfried Roemeratoe", "Juninho Bacuna", "Livano Comenencia", "Leandro Bacuna",
    "Tyrese Noslin", "Ar'jany Martha", "Kevin Felida", "Jürgen Locadia",
    "Jeremy Antonisse", "Sontje Hansen", "Kenji Gorré", "Jearl Margaritha",
    "Brandley Kuwas", "Gervane Kastaneer", "Tahith Chong",
  ],
  Ecuador: [
    "Hernán Galíndez", "Moisés Ramírez", "Gonzalo Valle",
    "Félix Torres", "Piero Hincapié", "Joel Ordóñez", "Willian Pacho",
    "Pervis Estupiñán", "Ángelo Preciado", "Jackson Porozo", "Jordy Alcívar",
    "Anthony Valencia", "John Yeboah", "Kendry Páez", "Alan Minda",
    "Pedro Vite", "Denil Castillo", "Gonzalo Plata", "Alan Franco",
    "Moisés Caicedo", "Yaimar Medina", "Kevin Rodríguez", "Enner Valencia",
    "Jordy Caicedo", "Nilson Angulo", "Jeremy Arévalo",
  ],
  EEUU: [
    "Matt Turner", "Matt Freese", "Chris Brady",
    "Sergiño Dest", "Antonee Robinson", "Chris Richards", "Tim Ream",
    "Miles Robinson", "Mark McKenzie", "Auston Trusty", "Joe Scally",
    "Max Arfsten", "Alex Freeman", "Tyler Adams", "Weston McKennie",
    "Gio Reyna", "Malik Tillman", "Sebastian Berhalter", "Cristian Roldan",
    "Christian Pulisic", "Folarin Balogun", "Ricardo Pepi", "Tim Weah",
    "Haji Wright", "Brenden Aaronson", "Alejandro Zendejas",
  ],
  Egipto: [
    "Mohamed El Shenawy", "Mostafa Shobeir", "El Mahdi Soliman",
    "Mohamed Alaa", "Mohamed Hany", "Tarek Alaa", "Hamdy Fathy",
    "Rami Rabia", "Yasser Ibrahim", "Hossam Abdelmaguid", "Mohamed Abdelmonem",
    "Ahmed Fatouh", "Karim Hafez", "Marwan Attia", "Mohanad Lasheen",
    "Nabil Emad", "Mahmoud Saber", "Ahmed Zizo", "Emam Ashour",
    "Mostafa Ziko", "Mahmoud Trezeguet", "Ibrahim Adel", "Haitham Hassan",
    "Omar Marmoush", "Mohamed Salah", "Hamza Abdelkarim",
  ],
  Escocia: [
    "Craig Gordon", "Angus Gunn", "Liam Kelly",
    "Grant Hanley", "Jack Hendry", "Aaron Hickey", "Dom Hyam",
    "Scott McKenna", "Nathan Patterson", "Anthony Ralston", "Andy Robertson",
    "John Souttar", "Kieran Tierney", "Ryan Christie", "Finlay Curtis",
    "Lewis Ferguson", "Ben Doak", "Tyler Fletcher", "John McGinn",
    "Kenny McLean", "Scott McTominay", "Ché Adams", "Lyndon Dykes",
    "George Hirst", "Lawrence Shankland", "Ross Stewart",
  ],
  España: [
    "Unai Simón", "David Raya", "Joan García",
    "Aymeric Laporte", "Marc Cucurella", "Marcos Llorente", "Eric García",
    "Pedro Porro", "Álex Grimaldo", "Pau Cubarsí", "Marc Pubill",
    "Rodri", "Fabián Ruiz", "Mikel Merino", "Pedri", "Gavi",
    "Martín Zubimendi", "Álex Baena", "Ferran Torres", "Mikel Oyarzabal",
    "Dani Olmo", "Nico Williams", "Lamine Yamal", "Yéremy Pino",
    "Borja Iglesias", "Víctor Muñoz",
  ],
  Francia: [
    "Mike Maignan", "Brice Samba", "Robin Risser",
    "Lucas Digne", "Malo Gusto", "Lucas Hernández", "Théo Hernández",
    "Ibrahima Konaté", "Jules Koundé", "Maxence Lacroix", "William Saliba",
    "Dayot Upamecano", "N'Golo Kanté", "Manu Koné", "Adrien Rabiot",
    "Aurélien Tchouaméni", "Warren Zaïre-Emery", "Maghnes Akliouche", "Bradley Barcola",
    "Rayan Cherki", "Ousmane Dembélé", "Désiré Doué", "Jean-Philippe Mateta",
    "Kylian Mbappé", "Michael Olise", "Marcus Thuram",
  ],
  Ghana: [
    "Lawrence Ati-Zigi", "Joseph Anang", "Benjamin Asare",
    "Alidu Seidu", "Caleb Yirenkyi", "Jonas Adjetey", "Abdul Mumin",
    "Gideon Mensah", "Baba Rahman", "Jerome Opoku", "Derrick Luckassen",
    "Marvin Senaya", "Thomas Partey", "Kwasi Sibo", "Elisha Owusu",
    "Augustine Boakye", "Christopher Bonsu Baah", "Fatawu Issahaku", "Jordan Ayew",
    "Brandon Thomas-Asante", "Antoine Semenyo", "Iñaki Williams", "Kojo Oppong Peprah",
    "Kamaldeen Sulemana", "Ernest Nuamah", "Prince Kwabena Adu",
  ],
  Haití: [
    "Johny Placide", "Alexandre Pierre", "Josué Duverger",
    "Carlens Arcus", "Wilguens Paugain", "Duke Lacroix", "Martin Expérience",
    "Jean-Kévin Duverne", "Ricardo Adé", "Hannes Delcroix", "Keeto Thermoncy",
    "Carl Fred Sainté", "Leverton Pierre", "Danley Jean Jacques", "Jean-Ricner Bellegarde",
    "Woodensky Pierre", "Dominique Simon", "Don Deedson Louicius", "Josué Casimir",
    "Derrick Etienne", "Ruben Providence", "Duckens Nazon", "Frantzdy Pierrot",
    "Wilson Isidor", "Yassin Fortuné", "Lenny Joseph",
  ],
  Holanda: [
    "Mark Flekken", "Robin Roefs", "Bart Verbruggen",
    "Nathan Aké", "Denzel Dumfries", "Jorrel Hato", "Jurriën Timber",
    "Jan Paul van Hecke", "Micky van de Ven", "Virgil van Dijk", "Frenkie de Jong",
    "Marten de Roon", "Ryan Gravenberch", "Teun Koopmeiners", "Tijjani Reijnders",
    "Guus Til", "Quinten Timber", "Mats Wieffer", "Brian Brobbey",
    "Memphis Depay", "Cody Gakpo", "Justin Kluivert", "Noa Lang",
    "Donyell Malen", "Crysencio Summerville", "Wout Weghorst",
  ],
  Inglaterra: [
    "Jordan Pickford", "Dean Henderson", "James Trafford",
    "Reece James", "Ezri Konsa", "Jarell Quansah", "John Stones",
    "Marc Guéhi", "Dan Burn", "Nico O'Reilly", "Djed Spence",
    "Tino Livramento", "Declan Rice", "Elliot Anderson", "Kobbie Mainoo",
    "Jordan Henderson", "Morgan Rogers", "Jude Bellingham", "Eberechi Eze",
    "Harry Kane", "Ivan Toney", "Ollie Watkins", "Bukayo Saka",
    "Marcus Rashford", "Anthony Gordon", "Noni Madueke",
  ],
  Irak: [
    "Fahad Talib", "Jalal Hassan", "Ahmed Basil",
    "Hussein Ali", "Manaf Younis", "Ahmed Yahya", "Mustafa Saadoon",
    "Zaid Tahseen", "Rebin Sulaka", "Akam Hashim", "Merchas Doski",
    "Zaid Ismail", "Frans Putros", "Amir Al-Ammari", "Kevin Yakob",
    "Zidane Iqbal", "Aimar Sher", "Ibrahim Bayesh", "Ahmed Qasem",
    "Youssef Amyn", "Marko Farji", "Ali Jassim", "Ali Al-Hamadi",
    "Ali Yousef", "Aymen Hussein", "Mohanad Ali",
  ],
  Irán: [
    "Alireza Beiranvand", "Hossein Hosseini", "Payam Niazmand",
    "Danial Eiri", "Ehsan Hajsafi", "Saleh Hardani", "Hossein Kanaani",
    "Shoja Khalilzadeh", "Milad Mohammadi", "Ali Nemati", "Ramin Rezaeian",
    "Rouzbeh Cheshmi", "Saeid Ezatolahi", "Mehdi Ghaedi", "Saman Ghoddos",
    "Mohammad Ghorbani", "Alireza Jahanbakhsh", "Mohammad Mohebi", "Amir Mohammad Razzaghinia",
    "Mehdi Torabi", "Aria Yousefi", "Ali Alipour", "Dennis Dargahi",
    "Amirhossein Hosseinzadeh", "Mehdi Taremi", "Shahriar Moghanlou",
  ],
  Japón: [
    "Zion Suzuki", "Keisuke Osako", "Tomoki Hayakawa",
    "Yuto Nagatomo", "Shogo Taniguchi", "Ko Itakura", "Tsuyoshi Watanabe",
    "Takehiro Tomiyasu", "Hiroki Ito", "Ayumu Seko", "Yukinari Sugawara",
    "Junnosuke Suzuki", "Wataru Endo", "Junya Ito", "Daichi Kamada",
    "Ritsu Doan", "Ao Tanaka", "Keito Nakamura", "Kaishu Sano",
    "Takefusa Kubo", "Yuito Suzuki", "Koki Ogawa", "Daizen Maeda",
    "Ayase Ueda", "Kento Shiogai", "Keisuke Goto",
  ],
  Jordania: [
    "Yazeed Abulaila", "Nour Bani Attiah", "Abdallah Al-Fakhouri",
    "Mohammad Abu Hashish", "Abdallah Nasib", "Husam Abu Dahab", "Yazan Al-Arab",
    "Mohammad Abualnadi", "Salim Obaid", "Saed Al-Rosan", "Ihsan Haddad",
    "Anas Badawi", "Mohannad Abu Taha", "Noor Al-Rawabdeh", "Nizar Al-Rashdan",
    "Ibrahim Sa'deh", "Rajaei Ayed", "Amer Jamous", "Mohammad Al-Dawoud",
    "Mahmoud Al-Mardi", "Odeh Al-Fakhouri", "Musa Al-Tamari", "Mohammad Abu Zrayq",
    "Ali Azaizeh", "Ibrahim Sabra", "Ali Olwan",
  ],
  Marruecos: [
    "Yassine Bounou", "Munir Mohamedi", "Ahmed Reda Tagnaouti",
    "Achraf Hakimi", "Noussair Mazraoui", "Nayef Aguerd", "Chadi Riad",
    "Issa Diop", "Anass Salah-Eddine", "Zakaria El Ouahdi", "Youssef Belammari",
    "Redouane Halhal", "Sofyan Amrabat", "Azzedine Ounahi", "Bilal El Khannouss",
    "Ismael Saibari", "Neil El Aynaoui", "Samir El Mourabet", "Ayyoub Bouaddi",
    "Brahim Díaz", "Ayoub El Kaabi", "Abde Ezzalzouli", "Soufiane Rahimi",
    "Chemsdine Talbi", "Gessime Yassine", "Ayoube Amaimouni",
  ],
  México: [
    "Raúl Rangel", "Carlos Acevedo", "Guillermo Ochoa",
    "Jorge Sánchez", "César Montes", "Edson Álvarez", "Johan Vásquez",
    "Israel Reyes", "Mateo Chávez", "Jesús Gallardo", "Érik Lira",
    "Luis Romo", "Álvaro Fidalgo", "Orbelín Pineda", "Obed Vargas",
    "Gilberto Mora", "Luis Chávez", "Brian Gutiérrez", "Raúl Jiménez",
    "Alexis Vega", "Santiago Giménez", "Armando González", "Julián Quiñones",
    "César Huerta", "Guillermo Martínez", "Roberto Alvarado",
  ],
  Noruega: [
    "Ørjan Nyland", "Egil Selvik", "Sander Tangvik",
    "Kristoffer Ajer", "Julian Ryerson", "Leo Østigård", "Marcus Holmgren Pedersen",
    "David Møller Wolfe", "Fredrik Bjørkan", "Torbjørn Heggem", "Sondre Langås",
    "Henrik Falchener", "Martin Ødegaard", "Sander Berge", "Patrick Berg",
    "Kristian Thorstvedt", "Morten Thorsby", "Antonio Nusa", "Fredrik Aursnes",
    "Oscar Bobb", "Jens Petter Hauge", "Andreas Schjelderup", "Thelo Aasgaard",
    "Alexander Sørloth", "Erling Haaland", "Jørgen Strand Larsen",
  ],
  "Nueva Zelanda": [
    "Max Crocombe", "Alex Paulsen", "Michael Woud",
    "Francis De Vries", "Tyler Bindon", "Michael Boxall", "Joe Bell",
    "Marko Stamenić", "Liberato Cacace", "Finn Surman", "Ryan Thomas",
    "Tommy Smith", "Nando Pijnaker", "Sarpreet Singh", "Alex Rufer",
    "Matt Garbett", "Callum McCowatt", "Jesse Randall", "Callan Elliot",
    "Chris Wood", "Eli Just", "Kosta Barbarouses", "Ben Waine",
    "Ben Old", "Lachlan Bayliss", "Tim Payne",
  ],
  Panamá: [
    "Luis Mejía", "Orlando Mosquera", "César Samudio",
    "Amir Murillo", "José Córdoba", "César Blackman", "Andrés Andrade",
    "Éric Davis", "Roderick Miller", "Jiovany Ramos", "Jorge Gutiérrez",
    "Fidel Escobar", "Edgardo Fariña", "Aníbal Godoy", "Adalberto Carrasquilla",
    "Cristian Martínez", "Carlos Harvey", "José Luis Rodríguez", "César Yanis",
    "Yoel Bárcenas", "Alberto Quintero", "Azarías Londoño", "Ismael Díaz",
    "José Fajardo", "Tomás Rodríguez", "Cecilio Waterman",
  ],
  Paraguay: [
    "Gatito Fernández", "Orlando Gill", "Gastón Olveira",
    "Gustavo Gómez", "Juan José Cáceres", "Gustavo Velázquez", "Fabián Balbuena",
    "Júnior Alonso", "Omar Alderete", "José Canale", "Alexandro Maidana",
    "Andrés Cubas", "Damián Bobadilla", "Diego Gómez", "Matías Galarza",
    "Alejandro Romero Gamarra", "Braian Ojeda", "Maurício Magalhães", "Miguel Almirón",
    "Julio Enciso", "Antonio Sanabria", "Álex Arce", "Ramón Sosa",
    "Gabriel Ávalos", "Isidro Pitta", "Gustavo Caballero",
  ],
  Portugal: [
    "Diogo Costa", "José Sá", "Rui Silva",
    "Rúben Dias", "João Cancelo", "Nélson Semedo", "Nuno Mendes",
    "Diogo Dalot", "Gonçalo Inácio", "Renato Veiga", "Tomás Araújo",
    "Bernardo Silva", "Bruno Fernandes", "Rúben Neves", "Vitinha",
    "João Neves", "Matheus Nunes", "Samu Costa", "Cristiano Ronaldo",
    "Francisco Trincão", "João Félix", "Rafael Leão", "Gonçalo Guedes",
    "Gonçalo Ramos", "Pedro Neto", "Francisco Conceição",
  ],
  Qatar: [
    "Meshaal Barsham", "Mahmoud Abunada", "Salah Zakaria",
    "Pedro Miguel", "Boualem Khoukhi", "Ayoub Al Aloui", "Al Hashmi Al Hussein",
    "Sultan Al Braik", "Jassem Jaber", "Mohamed Al Mannai", "Lucas Mendes",
    "Issa Lai", "Homam Ahmed", "Ahmed Al Janhi", "Tahseen Mohammed",
    "Ahmed Fathi", "Ahmed Alaa", "Assim Madibo", "Karim Boudiaf",
    "Abdulaziz Hatem", "Almoez Ali", "Akram Afif", "Edmilson Junior",
    "Hassan Al Haydos", "Yusuf Abdurisag", "Mohammed Muntari",
  ],
  "RD Congo": [
    "Lionel Mpasi", "Timothy Fayulu", "Matthieu Epolo",
    "Chancel Mbemba", "Aaron Wan-Bissaka", "Axel Tuanzebe", "Arthur Masuaku",
    "Gédéon Kalulu", "Joris Kayembe", "Dylan Batubinsika", "Steve Kapuadi",
    "Aaron Tshibola", "Meschak Elia", "Samuel Moutoussamy", "Edo Kayembe",
    "Charles Pickel", "Gaël Kakuta", "Noah Sadiki", "Nathanaël Mbuku",
    "Ngal'ayel Mukau", "Brian Cipenga", "Cédric Bakambu", "Théo Bongonda",
    "Fiston Mayele", "Yoane Wissa", "Simon Banza",
  ],
  Senegal: [
    "Édouard Mendy", "Mory Diaw", "Yehvann Diouf",
    "Kalidou Koulibaly", "Abdoulaye Seck", "Moussa Niakhaté", "Ismaïl Jakobs",
    "Mamadou Sarr", "Antoine Mendy", "El Hadji Malick Diouf", "Krépin Diatta",
    "Idrissa Gana Gueye", "Pape Matar Sarr", "Pathé Ciss", "Pape Gueye",
    "Lamine Camara", "Habib Diarra", "Bara Sapoko Ndiaye", "Sadio Mané",
    "Bamba Dieng", "Nicolas Jackson", "Iliman Ndiaye", "Ismaïla Sarr",
    "Chérif Ndiaye", "Ibrahim Mbaye", "Assane Diao",
  ],
  Sudáfrica: [
    "Ronwen Williams", "Ricardo Goss", "Sipho Chaine",
    "Aubrey Modiba", "Khuliso Mudau", "Khulumani Ndamane", "Kamogelo Sebelebele",
    "Nkosinathi Sibisi", "Bradley Cross", "Samukele Kabini", "Olwethu Makhanya",
    "Thabang Matuludi", "Mbekezeli Mbokazi", "Ime Okon", "Oswin Appollis",
    "Thalente Mbatha", "Relebohile Mofokeng", "Jayden Adams", "Teboho Mokoena",
    "Themba Zwane", "Sphephelo Sithole", "Evidence Makgopa", "Tshepang Moremi",
    "Lyle Foster", "Thapelo Maseko", "Iqraam Rayners",
  ],
  Suecia: [
    "Viktor Johansson", "Kristoffer Nordfeldt", "Jacob Widell Zetterström",
    "Victor Lindelöf", "Hjalmar Ekdal", "Isak Hien", "Carl Starfelt",
    "Gabriel Gudmundsson", "Daniel Svensson", "Gustaf Lagerbielke", "Elliot Stroud",
    "Eric Smith", "Herman Johansson", "Lucas Bergvall", "Yasin Ayari",
    "Mattias Svanberg", "Jesper Karlström", "Besfort Zeneli", "Ken Sema",
    "Taha Ali", "Alexander Bernhardsson", "Viktor Gyökeres", "Alexander Isak",
    "Anthony Elanga", "Gustaf Nilsson", "Benjamin Nygren",
  ],
  Suiza: [
    "Gregor Kobel", "Yvon Mvogo", "Marvin Keller",
    "Manuel Akanji", "Nico Elvedi", "Ricardo Rodríguez", "Silvan Widmer",
    "Miro Muheim", "Aurèle Amenda", "Eray Cömert", "Luca Jaquez",
    "Granit Xhaka", "Johan Manzambi", "Remo Freuler", "Denis Zakaria",
    "Ardon Jashari", "Djibril Sow", "Christian Fassnacht", "Michel Aebischer",
    "Fabian Rieder", "Rubén Vargas", "Breel Embolo", "Noah Okafor",
    "Dan Ndoye", "Zeki Amdouni", "Cedric Itten",
  ],
  Túnez: [
    "Aymen Dahmen", "Sabri Ben Hassan", "Abdelmouhib Chamakh",
    "Montassar Talbi", "Dylan Bronn", "Omar Rekik", "Yan Valery",
    "Ali Abdi", "Moutaz Neffati", "Raed Chikhaoui", "Adam Arous",
    "Mohamed Amine Ben Hamida", "Ellyes Skhiri", "Hannibal Mejbri", "Anis Ben Slimane",
    "Mohamed Haj Mahmoud", "Rani Khedira", "Mortadha Ben Ouanes", "Ismaël Gharbi",
    "Elias Achouri", "Elias Saad", "Sebastian Tounekti", "Firas Chaouat",
    "Khalil Ayari", "Hazem Mastouri", "Rayan Elloumi",
  ],
  Turquía: [
    "Uğurcan Çakır", "Mert Günok", "Altay Bayındır",
    "Merih Demiral", "Zeki Çelik", "Çağlar Söyüncü", "Mert Müldür",
    "Ferdi Kadıoğlu", "Ozan Kabak", "Abdülkerim Bardakcı", "Eren Elmalı",
    "Samet Akaydın", "Hakan Çalhanoğlu", "Kaan Ayhan", "Orkun Kökçü",
    "İsmail Yüksek", "Salih Özcan", "Kerem Aktürkoğlu", "İrfan Can Kahveci",
    "Barış Alper Yılmaz", "Arda Güler", "Kenan Yıldız", "Yunus Akgün",
    "Oğuz Aydın", "Deniz Gül", "Can Uzun",
  ],
  Uruguay: [
    "Sergio Rochet", "Fernando Muslera", "Santiago Mele",
    "Guillermo Varela", "Ronald Araújo", "José María Giménez", "Santiago Bueno",
    "Sebastián Cáceres", "Mathías Olivera", "Joaquín Piquerez", "Matías Viña",
    "Manuel Ugarte", "Emiliano Martínez", "Rodrigo Bentancur", "Federico Valverde",
    "Agustín Canobbio", "Juan Manuel Sanabria", "Giorgian de Arrascaeta", "Nicolás de la Cruz",
    "Rodrigo Zalazar", "Facundo Pellistri", "Maximiliano Araújo", "Brian Rodríguez",
    "Rodrigo Aguirre", "Federico Viñas", "Darwin Núñez",
  ],
  Uzbekistán: [
    "Utkir Yusupov", "Abduvohid Nematov", "Botirali Ergashev",
    "Abdukodir Khusanov", "Khojiakbar Alijonov", "Farrukh Sayfiev", "Rustam Ashurmatov",
    "Umar Eshmurodov", "Sherzod Nasrullaev", "Abdulla Abdullaev", "Avazbek Ulmasaliev",
    "Jakhongir Urozov", "Bekhruz Karimov", "Akmal Mozgovoy", "Otabek Shukurov",
    "Jamshid Iskanderov", "Odil Khamrobekov", "Jaloliddin Masharipov", "Oston Urunov",
    "Dostonbek Khamdamov", "Aziz Ganiev", "Abbosbek Fayzullaev", "Sherzod Esanov",
    "Eldor Shomurodov", "Igor Sergeev", "Azizbek Omonov",
  ],
};

// Lista plana para alimentar el buscador del selector.
// Cada entrada: { nombre, equipo }. El `id` (clave de búsqueda y valor
// guardado) es "Nombre (Selección)" para evitar colisiones entre homónimos.
export const JUGADORES_LISTA = Object.entries(JUGADORES_MUNDIAL_2026)
  .flatMap(([equipo, jugadores]) =>
    jugadores.map((nombre) => ({ nombre, equipo })),
  )
  // Orden alfabético por nombre para una navegación predecible.
  .sort((a, b) => a.nombre.localeCompare(b.nombre, "es"));

// Valor canónico guardado para un goleador: "Nombre (Selección)".
// Lo usan por igual la apuesta del usuario y el resultado oficial del admin,
// de modo que la comparación de puntos (case-insensitive) siempre coincide.
export function goleadorValue(nombre, equipo) {
  return `${nombre} (${equipo})`;
}

// Opciones para el <SearchSelect> de goleador: { value, label, sublabel, code }.
// `code` se resuelve con el helper de banderas de constants.js.
export const GOLEADOR_OPTIONS = JUGADORES_LISTA.map(({ nombre, equipo }) => ({
  value: goleadorValue(nombre, equipo),
  label: nombre,
  sublabel: equipo,
  code: code(equipo),
}));
